### ISSUE TITLE
Broken Link in Gamepy/index.html

### ISSUE THREAD

**Issue by v-for-vasya** [drvinceknight/Gamepy#1]
On line 22 of Gamepy/index.html the personal website link is missing an http:// in front of the  www which prevents the link from transferring to your website.

**Comment by drvinceknight** [comment]
Thanks @v-for-vasya, I am not encouraging use of this library. I have in fact just changed the README with a variety of better alternatives. Please get in touch if you'd like to use any of them or indeed contribute to any of them and if I can help :)
